name: Sprawdzanie
main: me.iedsa2.sprawdzanie.Main
version: 1.0
api-version: 1.20
commands:
  sprawdz:
    description: Sprawdzanie gracza
  setroomsprawdzanie:
    description: Ustawia pokoj sprawdzania
  przyznajesie:
    description: Przyznanie sie gracza
